// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msowbpgiogzxyedaqicf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zb3dicGdpb2d6eHllZGFxaWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NDgyNDIsImV4cCI6MjA4NjIyNDI0Mn0.6kirG9pPRaO3_Q1rBGqqBggsG9ODtg3YGyzwakUGi8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});